#:kivy 2.1.0
<TitleScreen>:
    BoxLayout:
        BoxLayout:
            orientation: 'vertical'
            size: root.size
            Label:
                text:'make8'
            BoxLayout:

                Button:
                    text: 'Move to MainView'
                    on_press: root.manager.current = 'main'
            BoxLayout:
                Button:
                    text: 'Close'

<MainScreen>:
    BoxLayout:
        BoxLayout:
            orientation: 'vertical'
            size: root.size
            Button:
                text:'retire'
                size_hint_y:0.1
                size_hint_x:0.1
                on_press: root.manager.current = 'title'
            Label:
                text:'question'
            Label:
                id: label1
                text:''
            BoxLayout:
                size_hint_y: 0.2
                Button:
                    id: button1
                    text: 'one'
                    on_press: root.onPress()
                Button:
                    text: 'two'
                Button:
                    text: 'three'
                Button:
                    text: 'four'
                Button:
                    text: 'Delete'
                    on_press: root.manager.current = 'title'

            BoxLayout:
                size_hint_y: 0.2
                Button:
                    text: '+'
                Button:
                    text: '-'
                Button:
                    text: '*'
                Button:
                    text: '/'
                Button:
                    text: 'OK'
                    on_press: root.manager.current = 'title'


<WrongAnsScreen>

<RetireScreen>
    BoxLayout:
        BoxLayout:
            orientation: 'vertical'
            size: root.size
            Label:
                text:'答えは'
            Label:
                text:'2+2+2+2'
            Label:
                text:'他にも答えがあるかもしれません'
            BoxLayout:

                Button:
                    text: 'Move to TitleView'
                    on_press: root.manager.current = 'title'

<CorrectScreen>
    BoxLayout:
        BoxLayout:
            orientation: 'vertical'
            size: root.size
            Label:
                text:'Clear!!'
            BoxLayout:

                Button:
                    text: 'Move to MainView'
                    on_press: root.manager.current = 'main'
            BoxLayout:
                Button:
                    text: 'Move to title'

