#:kivy 1.0
#:include kv/title.kv
#:include kv/retire.kv
#:include kv/playing.kv
#:include kv/correct.kv


<Failpopup>:
    auto_dismiss: False
    size_hint: .5, .5
    pos_hint: {'center_x': .5, 'center_y': .5}
    title: 'まだやれる！がんばれ！'
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: 'Your answer is wrong'
        Button:
            size_hint_y: None
            height: 80
            text: 'とじる'
            on_release: root.dismiss()

# ボタンデザイン
<Btn@Button>:
    background_color:(0,0,0,0)
    background_normal:''
    text_size: self.width, None
    halign: 'center'
    canvas.before:
        Color:
            rgba:(5/255,219/255,242/255,1) if self.state=='down' else (11/255,59/255,89/255,1)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius:[18]

<MenuBtn@Btn>:
    font_size: 170*self.width/1600

<GameBtn@Btn>:
    font_size: 120*self.width/400

# ラベルデザイン
<Lbl@Label>:
    color: 240/255, 241/255, 242/255, 1

# 背景付きラベル
<BackgroundColor@Widget>:
    background_color: 1, 1, 1, 1
    canvas.before:
        Color:
            rgba: root.background_color
        Rectangle:
            size: self.size
            pos: self.pos

<BgLbl@Label+BackgroundColor>:
    background_color: 240/255, 241/255, 242/255, 1
    color: 11/255, 59/255, 89/255, 1
