#:kivy 1.0

<Retire>:
    # 背景
    canvas.before:
        Color:
            rgba: 17/255, 93/255, 140/255, 1
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: 'vertical'
        size: root.size

        BoxLayout:
            orientation: 'vertical'
            size: root.size
            Lbl:
                text:'答えは...'
                font_size: 70*self.width/1600
            Lbl:
                id: answer
                text:'2+2+2+2'
                font_size: 170*self.width/1600

            Lbl:
                text:'(他にも答えがあるかもしれません)'
                font_size: 50*self.width/1600
        
        BoxLayout:
            orientation: 'vertical'
            padding: [0,100]
            spacing: 50

            MenuBtn:
                text: 'タイトルへ'
                on_release: app.onClick('title')
                size_hint: (.3 , .15)
                pos_hint: {'center_x': .5, 'center_y': .5} 
            MenuBtn:
                text: 'おわる'
                on_release : app.stop()
                size_hint: (.3 , .15)
                pos_hint: {'center_x': .5, 'center_y': .5}